#!/usr/bin/env python3
"""
Create a draft V3 journal entry in `.ai/v3/journals/drafts/`.

P2 fixes (2026-05-29):
- #7: validate --v3-id with regex + path safety
- #8: verification facts default to false (explicit true required)
- #9: enforce journal invariants (failed/blocked → empty imported, duplicates, overlap)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import subprocess
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]

THIS_DIR = Path(__file__).resolve().parent
V3_ID_PATTERN = re.compile(r"^V3-\d{8}-\d{6}-[a-z0-9][a-z0-9-]*$")

JOURNAL_TEMPLATE = """\
# V3 Journal Entry — {v3_id}
#
# Auto-generated by scripts/v3/write_v3_journal.py
# This is a draft. Located in `.ai/v3/journals/drafts/`.
# Until human accept, journal is not tracked and not an accepted artifact.

v3_id: "{v3_id}"
timestamp: "{timestamp}"
import_status: "{import_status}"

source_package:
  package_id: "{package_id}"
  source_type: "{source_type}"
  source_value: "{source_value}"
  manifest_path: "{manifest_path}"
  zip_archive: "{zip_archive}"
  checksums_verified: {checksums_verified}

imported_files:
{imported_files}

skipped_files:
{skipped_files}

verification_notes:
  manifest_valid: {manifest_valid}
  all_files_in_manifest: {all_files_in_manifest}
  no_extra_files: {no_extra_files}
  checksums_all_match: {checksums_all_match}
  allowed_paths_valid: {allowed_paths_valid}
  forbidden_paths_respected: {forbidden_paths_respected}

human_review_status: "pending"
"""


def _fail(msg: str, code: int = 1) -> None:
    print(f"FAIL: {msg}", file=sys.stderr)
    raise SystemExit(code)


def _ok(msg: str) -> None:
    print(f"  OK: {msg}")


def _repo_root() -> Path:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, cwd=THIS_DIR, check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        _fail("Cannot determine git repo root.")
    return Path(result.stdout.strip())


def _ensure_yaml() -> None:
    if yaml is None:
        _fail("PyYAML not installed. Install: pip install pyyaml")


def _validate_v3_id(value: str) -> str:
    """Issue #7: strict V3 ID validation + path safety."""
    if not V3_ID_PATTERN.match(value):
        _fail(f"Invalid --v3-id `{value}`. Must match V3-YYYYMMDD-HHMMSS-<slug>.")
    if ".." in Path(value).parts:
        _fail(f"--v3-id `{value}` contains path traversal.")
    return value


def _validate_journal_invariants(
    import_status: str,
    imported_files: list[dict],
    skipped_files: list[dict],
) -> None:
    """Issue #9: enforce journal contract invariants."""
    # If failed or blocked, imported_files must be empty
    if import_status in ("failed", "blocked") and imported_files:
        _fail(
            f"import_status={import_status} but imported_files is not empty "
            f"({len(imported_files)} items). Contract requires empty imported_files."
        )

    # No duplicates in imported_files
    imported_paths = [item.get("path", "") for item in imported_files]
    if len(imported_paths) != len(set(imported_paths)):
        _fail("imported_files contains duplicate paths.")

    # No duplicates in skipped_files
    skipped_paths = [item.get("path", "") for item in skipped_files]
    if len(skipped_paths) != len(set(skipped_paths)):
        _fail("skipped_files contains duplicate paths.")

    # No overlap between imported and skipped
    overlap = set(imported_paths) & set(skipped_paths)
    if overlap:
        _fail(
            "Files appear in both imported_files and skipped_files: "
            + ", ".join(f"`{p}`" for p in sorted(overlap))
        )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Create draft V3 journal in .ai/v3/journals/drafts/.")
    p.add_argument("--template", action="store_true", help="Print template and exit.")
    p.add_argument("--write", action="store_true", help="Write draft journal.")
    p.add_argument("--v3-id", help="V3 ID (V3-YYYYMMDD-HHMMSS-<slug>).")
    p.add_argument("--import-status", default="imported",
                   choices=["imported", "partial", "failed", "blocked"])
    p.add_argument("--package-id", help="Package ID from manifest.")
    p.add_argument("--source-type", default="local_archive_path")
    p.add_argument("--source-value", help="Link or path to archive.")
    p.add_argument("--manifest-path", help="Manifest path inside staging.")
    p.add_argument("--zip-archive", help="Path to saved ZIP.")
    p.add_argument("--checksums-verified", default="false", choices=["true", "false"])
    p.add_argument("--imported-files", default="", help="JSON list of imported files.")
    p.add_argument("--skipped-files", default="", help="JSON list of skipped files.")

    # Issue #8: verification flags default to false
    for flag in ("manifest-valid", "all-files-in-manifest", "no-extra-files",
                 "checksums-all-match", "allowed-paths-valid", "forbidden-paths-respected"):
        p.add_argument(f"--{flag}", default="false", choices=["true", "false"])

    p.add_argument("--root", default=None, help="Git repo root.")
    return p


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")

    args = build_parser().parse_args()

    if args.template:
        print(JOURNAL_TEMPLATE.format(
            v3_id="V3-YYYYMMDD-HHMMSS-<slug>",
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            import_status="imported",
            package_id="V3-YYYYMMDD-HHMMSS-<slug>",
            source_type="local_archive_path",
            source_value="/path/to/package.zip",
            manifest_path="V3-YYYYMMDD-HHMMSS-<slug>/manifest.yaml",
            zip_archive="/path/to/package.zip",
            checksums_verified="false",
            imported_files="  []", skipped_files="  []",
            manifest_valid="false", all_files_in_manifest="false",
            no_extra_files="false", checksums_all_match="false",
            allowed_paths_valid="false", forbidden_paths_respected="false",
        ))
        return 0

    if not args.write:
        _fail("Specify --write or --template.")

    if not args.v3_id:
        _fail("--v3-id is required.")

    # Issue #7: validate V3 ID
    v3_id = _validate_v3_id(args.v3_id)

    _ensure_yaml()
    root = Path(args.root).resolve() if args.root else _repo_root()
    drafts_dir = root / ".ai" / "v3" / "journals" / "drafts"
    drafts_dir.mkdir(parents=True, exist_ok=True)

    journal_path = drafts_dir / f"{v3_id}_journal.yaml"

    # Issue #7: ensure resolved path stays inside drafts_dir
    try:
        journal_path.resolve().relative_to(drafts_dir.resolve())
    except ValueError:
        _fail(f"Journal path `{journal_path}` escapes drafts directory.")

    if journal_path.exists():
        _fail(f"Draft journal already exists: `{journal_path}`.")

    imported_files = json.loads(args.imported_files) if args.imported_files else []
    skipped_files = json.loads(args.skipped_files) if args.skipped_files else []

    # Issue #9: enforce invariants
    _validate_journal_invariants(args.import_status, imported_files, skipped_files)

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    journal_data = {
        "v3_id": v3_id,
        "timestamp": now_utc,
        "import_status": args.import_status,
        "source_package": {
            "package_id": args.package_id or v3_id,
            "source_type": args.source_type,
            "source_value": args.source_value or "",
            "manifest_path": args.manifest_path or f"{v3_id}/manifest.yaml",
            "zip_archive": args.zip_archive or "",
            "checksums_verified": args.checksums_verified == "true",
        },
        "imported_files": imported_files,
        "skipped_files": skipped_files,
        "verification_notes": {
            "manifest_valid": args.manifest_valid == "true",
            "all_files_in_manifest": args.all_files_in_manifest == "true",
            "no_extra_files": args.no_extra_files == "true",
            "checksums_all_match": args.checksums_all_match == "true",
            "allowed_paths_valid": args.allowed_paths_valid == "true",
            "forbidden_paths_respected": args.forbidden_paths_respected == "true",
        },
        "human_review_status": "pending",
    }

    with open(journal_path, "w", encoding="utf-8") as fh:
        yaml.dump(journal_data, fh, allow_unicode=True, default_flow_style=False, sort_keys=False)

    _ok(f"Draft journal created: {journal_path}")
    print(f"\nPASS: V3 journal draft written.")
    print(f"Journal: {journal_path}")
    print("V3_navigation.md NOT modified.")
    print("Project files NOT modified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
